### ISSUE TITLE
here's an updated fork for 2022 Dlang

### ISSUE THREAD

**Issue by redthing1** [rcorre/dtiled#10]
https://github.com/redthing1/dtiled-redthing1

**Comment by rcorre** [comment]
Thanks! If you open a PR I'd be happy to create a new release

**Comment by redthing1** [comment]
> Thanks! If you open a PR I'd be happy to create a new release

Sure!

**Comment by redthing1** [comment]
https://github.com/rcorre/dtiled/pull/11

**Comment by rcorre** [comment]
Closed by #10.
