### ISSUE TITLE
Dtiled going crazy when trying out "loading a map" example using Dgame

### ISSUE THREAD

**Issue by Jackoz530** [rcorre/dtiled#6]
Well to start, I just copied the code for loading the map and tried to build it, substituting the variables like Rect and others.

Then it went crazy all of a sudden:

http://dpaste.com/2D59A2B

The whole thing went mad, and I was sure I had my imports correct:

import dtiled.data;
import dtiled.map;
import dtiled.grid;
import dtiled.algorithm;
import dtiled.coords;

import Dgame.Math.Rect;
import Dgame.Math.Vector2;
import Dgame.Math.Geometry;
import Dgame.Math.Vertex;

And that's where I was left dumbfounded. I use the latest D compiler, and the latest dub. Dmd v.2.069.1 and dub v.0.9.24

**Comment by rcorre** [comment]
I forgot to account for the fact that `size_t` is `uint`, not `ulong` on Windows.
Should be fixed in `v0.3.1`. Let me know if that works.
Thanks for reporting!

**Comment by Jackoz530** [comment]
Thank you for replying so quickly. The implicit conversion issue went away.
Though there's still the "unidentified identifier data" error. 
Anyway thank you.

Edit:
There's a typo for your loading a map example.
It should not be data, rather it should be mapData.
And there is no property chunks for mapData
This is the error code:
http://dpaste.com/1P3NV00

I think I'm doing something wrong here.

**Comment by rcorre** [comment]
> There's a typo for your loading a map example.
> It should not be data, rather it should be mapData.

So there was; thanks!

> And there is no property chunks for mapData.

[`chunks`](http://dlang.org/phobos/std_range.html#.chunks) is part of `std.range`, try importing that (I didn't explicitly show all the imports in my example).

If it helps to have an actual working example, check out [dtiled-example](https://github.com/rcorre/dtiled-example), which I just verified with the most recent `dtiled` (assuming there are no more Windows incompatibilities).

**Comment by Jackoz530** [comment]
Yep, the chunks error is gone. Thank you. 

Though there's a number of inconsistencies in dtiled-example when I tried to build it.
For Dgame"
![dgame_inconsistency](https://cloud.githubusercontent.com/assets/10094438/11455048/f04c973e-9683-11e5-9bc6-a03078395144.PNG)
For Allegro:
![allegro inconsitency](https://cloud.githubusercontent.com/assets/10094438/11455049/f0c3a22a-9683-11e5-9b64-51e9ab711830.PNG)

**Comment by rcorre** [comment]
Pushed up `v0.3.2` which should fix the rounding issue on Windows (hopefully, though I don't have a Windows environment set up to test right now).

Not sure about the DGame issue, it almost looks like those warnings are coming from DGame itself, though I could be wrong.

**Comment by Jackoz530** [comment]
Can we continue this by email? I need help understanding dtiled-example's code.
If not, I suppose some insight on how you handled two layers on tilemap.d would be appreciated.
I've been okay for about one layer only, but I'm having trouble understanding how you implemented the two layers.

**Comment by rcorre** [comment]
Sure.

Take a look at the `Tile` struct in `tilemap.d` (in dtiled-example).
It contains two Rects, `terrainRect` and `featureRect`.

In Tiled, I've created two layers, "Ground" and "Features" (maybe I should have
called "Ground" "Terrain" for consistency, oops). In `buildMap`, I load the data
for both of these layers, each of which is just a list of GIDs. I then use `zip`
to pair each ground GID with the feature GID for each tiled. For example, the
first element would be [1, 12]. 1 is the ground GID, indicating grass, and 12 is
the feature GID, indicating a tree.

This is just a linear range, so I use `chunks` to group together rows. Then, for
each pair of GIDs in a row, I create a Tile. The Tile constructor takes the two
GIDs as well as a reference to the tileset, so it can look up a rect in the
spritesheet for each GID. For example, the GID '1' would translate to the rect
[0,0,32,32], which maps to the grass tile in the upper left of the tileset.

Hopefully this clears some things up. Admittedly its not documented as well as
it could be, I'd really like to do a step-by-step tutorial when I find some
time. Thanks for asking though, its good to know what people get tripped up on.

**Comment by rcorre** [comment]
Oops, was trying to reply to your email but it just went here. Well, maybe it will be useful to anyone who stumbles over this.
If the Windows compiler errors/warnings are resolved, I'll go ahead and close this.

**Comment by Jackoz530** [comment]
The window compiler errors/warnings in the Demo still stands but I have no problems in utilizing the library. Thank you for helping.

Maybe I'll make a newbie friendly tutorial someday if you don't mind. This is a very useful library.
Yes please close this. If you don't mind I'll drop a message here if I still need help in utilizing it.

**Comment by rcorre** [comment]
> The window compiler errors/warnings in the Demo still stands

Hopefully I'll have a Windows environment set up soon so I can resolve these.

> Maybe I'll make a newbie friendly tutorial someday if you don't mind

That would be great! 

> If you don't mind I'll drop a message here if I still need help in utilizing it

Sure thing. It helps me to know where people get tripped up, so let me know if anything seems confusing.
